config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users, only: [:show, :index]
  resources :pets
  resources :pet_pets

  patch '/battle', to: 'users#battle', as: 'battle'
  patch '/adopt', to: 'pets#adopt', as: 'adopt'
  patch '/feed', to: 'pets#feed', as: 'feed'
  get '/adoption_agency', to: 'pets#index', as: 'adoption_agency'
  get '/new_neopet', to: 'pets#new_neopet', as: 'new_neopet'
  post '/create', to: 'pets#create', as: 'create'
  get '/new_petpet', to: 'pet_pets#new_petpet', as: 'new_petpet'
  post '/createpetpet', to: 'pets#createpetpet', as: 'createpetpet'
end

app/models/pet.rb
# == Schema Information
#
# Table name: pets
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  color      :string(255)
#  hunger     :integer
#  loyalty    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Pet < ActiveRecord::Base
	belongs_to :user
	has_many :pet_pets

	validates :name, presence: true
	validates :name, length: { in: 3..20 }
	validates :color, presence: true    
end

app/models/pet_pet.rb
# == Schema Information
#
# Table name: pet_pets
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  color      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class PetPet < ActiveRecord::Base
	belongs_to :pet

	validates :name, presence: true 
	validates :name, length: { in: 3..20 }
	validates :color, presence: true  
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pets
  validates :name, presence: true       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pet_pets_controller.rb
class PetPetsController < ApplicationController
	def new_petpet
		@id = params[:pet_id]
		puts 5
		puts params
	end

	def create
		@pet = Pet.find(params[:id])
		@pet_pet = PetPet.new(pet_pet_params)
		@pet_pet.pet_id = @pet.id
		@pet_pet.save
		redirect_to user_path(User.find(Pet.find(params[:id]).user_id))
	end

	def index
		@pet_pet = PetPet.all
	end


	def show
		@pet_pet = PetPet.find params[:id]
	end

	private

	def pet_pet_params
		params.require(:pet_pet).permit(:name, :color)
	end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
	def new
		@id = params[:id]
	end

	def adopt
		@pet = Pet.find(params[:id])
		@pet.user_id = current_user.id
		@user = User.find(@pet.user_id)
		if @user.neocoin == nil
			@user.neocoin = 3
		else
			@user.neocoin += 3
		end	
		@user.save
		if @pet.save
			redirect_to user_path(@pet.user_id)
		end
	end

	def feed
		@pet = Pet.find(params[:id])
		@user = User.find(@pet.user_id)
		if @user.neocoin <= 0
			flash[:error] = @pet.errors.full_messages.to_sentence
		else
			@user.neocoin -= 1
			@pet.hunger += 10
		end
		@user.save
		@pet.save
		redirect_to user_path(@pet.user_id)
	end

	def create
		@pet = Pet.new(pet_params)
		@pet.hunger = 50
		@pet.loyalty = 50
		@pet.user_id = current_user.id
		if @pet.save
			redirect_to user_path(User.find(@pet.user_id))
		else
			flash[:error] = @pet.errors.full_messages.to_sentence
			redirect_to user_path(User.find(@pet.user_id))
		end
	end

	def createpetpet
		@pet = Pet.find(params[:id])
		@pet_pet = PetPet.new(pet_pet_params)
		@pet_pet.pet_id = @pet.id
		@pet_pet.save
		redirect_to user_path(User.find(Pet.find(params[:id]).user_id))
	end

	def index
    	@pets = Pet.all
  	end

	def show
		@pet = Pet.find params[:id]
	end

	private

	def pet_params
		params.require(:pet).permit(:name, :color)
	end

	def pet_pet_params
		params.require(:pet_pet).permit(:name, :color)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

  def battle
    @pet = Pet.find(params[:id])
    success_rate = Random.new.rand(1..100)
    # if (success_rate <= 75)
      @pet.hunger -= 5
      @pet.loyalty += 10
      @user = User.find(@pet.user_id)
      @user.neocoin += 1
    # else
    #   @pet.hunger -= 5
    #   @pet.loyalty -= 15   
    # end
    @user.save
    @pet.save
    redirect_to user_path(@pet.user_id)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pet_pets_helper.rb
module PetPetsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<link href='http://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Adoption Agency', adoption_agency_path %></li>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Neopet" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Neopet" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pet_pets/new_petpet.html.erb
<p>
<p>
<div class="row">
	<div class="col-lg-12">
		<center>
<%= simple_form_for PetPet.new, :url => createpetpet_path(id: @id) do |f| %>
    <%= f.input :name %>
    <%= f.input :color %>
    <%= f.button :submit %>
<% end %>
</center>
</div>
</div>

app/views/pets/index.html.erb
<div class="container">
  <div class="row">
    <h3>Pets</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @pets.each do |pet| %>
            <tr>
              <td><%= link_to pet.name, pet %></td>
              <td><%= link_to pet.color, pet %></td>
              <td><%= button_to "Adopt this pet!", adopt_path(id: pet), :class => "button small", :method => :patch %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/pets/new_neopet.html.erb
<p>
<p>
<div class="row">
	<div class="col-lg-12">
		<center>
	<%= simple_form_for Pet.new, :url => create_path do |f| %>
    <%= f.input :name %>
    <%= f.input :color %>
    <%= f.button :submit %>
<% end %>
</center>
</div>
</div>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<link href='http://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>

<center><h2><u><b>Profile</b></u></h2></center>
<section class="profile" id="profile">
	<div class="row">
		<div class="col-xs-4 col-sm-4">
			<div class="newnp">
				<div class="buttonwrap">
			<%= button_to "Create a Custom Neopet!", new_neopet_path, :class => "button medium", :method => :get %>
		</div>
			</div>
		</div>
		<div class="col-xs-4 col-sm-4">
			<div class="info">
			<p>Name: <%= @user.name if @user.name %></p>
			<p>Email: <%= @user.email if @user.email %></p>
			<p>Neocoins: <%= @user.neocoin if @user.neocoin %></p>
			</div>
		</div>
	</div>
</section>
 
 <section class="pets">
 	<div class="row">
 		<div class="col-lg-12">
 			<h1><u>Pets</u><h1>
 			</div>
 		</div>
 		<div class="row">
 <% @user.pets.each do |pet| %>
  			<div class="col-sm-4">
      <span class="petname"><%= pet.name %>,</span> 
      	<ul>Color <%= pet.color %>,</ul> 
      	<ul> Hunger <%= pet.hunger %>,</ul> 
      	<ul> Loyalty <%= pet.loyalty%>, </ul> 
      	<ul><%= button_to "Battle!", battle_path(id: pet), :class => "button medium", :method => :patch %>,</ul> 
      	<ul><%= button_to "Feed Neopet", feed_path(id: pet), :class => "button medium", :method => :patch %>,</ul> 
      	<ul><span class="createpetpet"><%= link_to "Create a Petpet!", new_petpet_path(:pet_id => pet.id), :class => "button medium", :method => :get %></span></ul>
      	<b>My PetPets:</b>
      <% pet.pet_pets.each do |pet_pet| %>
      	Name: <%= pet_pet.name %>,  Color <%= pet_pet.color %>
      	<% end %>
      </div>
 <% end %>
</div>
</div>
</section>

app/views/visitors/index.html.erb
<!-- Custom fonts -->
<link href='http://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>


<div class="header2">
	<div class="row">
		<div class="col-lg-12">
			<div class="title-text">
				<span class="title">neopet</span>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<span class="users"><p><%= link_to 'Users:', users_path, :class=>"userslink" %> <%= User.count %> registered</p></span>
	</div>
</div>